services:
  sc2bot:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    depends_on:
      - web-backend-sc2
    volumes:
      - "${SC_PATH}:/root/StarCraftII:z"
      # - "${WINE_PATH}:/root/.wine/:z"
      - ./bot:/bot:z
      - "${SC2_DOCUMENTS}:/root/Documents/StarCraftII:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: [
      "python", "/bot/cannon_rush.py"]
    environment: 
      - DISPLAY
      - MAP=${MAP}
      - "PYTHONUNBUFFERED=1"
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
    privileged: true
    network_mode: host


  web-backend-sc2:
    image: web-backend-sc2
    container_name: web-backend-sc2
    build:
      network: host
      context: ./web-server-sc2/backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - ./web-server-sc2/backend/sc2_websocket_bridge:/app/sc2_websocket_bridge
      - ./bot/data/:/app/data/:ro
    command: ["sc2_web", "--port", "8000", "--host", "0.0.0.0", "--data_path", "/app/data/"]

  web-frontend-sc2:
    image: web-frontend-sc2
    container_name: web-frontend-sc2
    depends_on:
      - web-backend-sc2
    build:
      network: host
      context: ./web-server-sc2/frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes: 
      - ./web-server-sc2/frontend/src:/app/src:rw
      - ./web-server-sc2/frontend/static:/app/static:ro