services:
  sc2bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${SC_PATH}:/root/StarCraftII:z"
      # - "${WINE_PATH}:/root/.wine/:z"
      - ./bot:/bot:z
      - "${SC2_DOCUMENTS}:/root/Documents/StarCraftII:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: [
      "python", "/bot/cannon_rush.py"]
    environment: 
      - DISPLAY
      - MAP=${MAP}
      - "PYTHONUNBUFFERED=1"
      # - SC2PF=${SC2PF}
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
    privileged: true